import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import RenderTable from "./RenderTable";
const people = [
    {
        stdId: "Lindsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Walton1",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa1",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Wa1",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Walton2",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa2",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Wa2",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Walton3",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa3",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Wa3",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Walton4",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa4",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay W4a",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Walto5n",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind5sa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay 5Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay Wa6lton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linds87a",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay 87Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay 76Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind23sa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay11 Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind1say Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lin2dsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linds12ay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa211`3y Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind54sa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsa453y Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind64say Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linds43a",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind43say Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind34say Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind34sa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay1 Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsay 34Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsahgs",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsaysfg Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsaysawe Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsafdsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linddfsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindfadsersay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindatregasa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindafretsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindartfgreafvsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind sa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linafgfadsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindsagreay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindatrsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lintgrdfedsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lingaertdsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linreagbfgdsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindgvzregvrfc csay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind4365say Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linds464556a",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lin2645345dsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linds26453ay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lin46345bngfdsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lin543543dsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lin453453fgfdsdsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind45543 ggsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindffd5343643dsay Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lind543443fghdfsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linstrewrtredsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lindswertrewway Wa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Linrterwt45redsay Walton",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
    {
        stdId: "Lintre6tretrdsa",
        stdName: "Front-end Developer",
        class: "lindsay.walton@example.com",
        faculty: "Member",
        sec: "Lindsay Walton",
        gen: "Front-end Developer",
        numb: "lindsay.walton@example.com",
        status: "Member",
    },
];
export default function Table() {
    const itemsOnPage = 5;
    const [currentPage, setCurrentPage] = useState(1);
    const [currentItems, setCurrentItems] = useState(people.slice(0, itemsOnPage));
    const [indexOfLastItem, setIndexOfLastItem] = useState(currentPage * itemsOnPage);
    const [indexOfFirstItem, setIndexOfFirstItem] = useState(indexOfLastItem - itemsOnPage);
    const [message, setmessage] = useState("Showing 1 to 2 of 2 results");
    const onNextPage = () => {
        setCurrentPage((curr) => curr + 1);
    };
    const onPreviousPage = () => {
        setCurrentPage((curr) => curr - 1);
    };
    useEffect(() => {
        setIndexOfLastItem(currentPage * itemsOnPage);
    }, [currentPage]);
    useEffect(() => {
        setIndexOfFirstItem(indexOfLastItem - itemsOnPage);
    }, [indexOfLastItem]);
    useEffect(() => {
        setmessage(`Showing ${indexOfFirstItem + 1} to ${people.length <= indexOfLastItem ? people.length : indexOfLastItem} of ${people.length}`);
        setCurrentItems(people.slice(indexOfFirstItem, indexOfLastItem));
    }, [indexOfFirstItem]);
    return (_jsxs("div", { className: "mt-11", children: [_jsxs("div", { className: "sm:flex sm:items-center", children: [_jsxs("div", { className: "sm:flex-auto", children: [_jsx("h1", { className: "text-primary-grey-700 text-xl font-semibold", children: "Student Details" }), _jsx("p", { className: "mt-2 text-sm text-gray-700", children: "A list of all the users in your account including their name, title, email and role." })] }), _jsx("div", { className: "sm:mt-0 sm:ml-16 sm:flex-none mt-4", children: _jsx(Link, { to: "/admin/dashboard/student/student-information/add-student-details", className: "primary_btn", children: "Add Student" }) })] }), _jsx("div", { className: "my-6", children: _jsx("div", { className: " ring-1 ring-black ring-opacity-5 min-w-full overflow-x-auto rounded-lg shadow", children: _jsx("div", { className: "inline-block w-full align-middle", children: _jsx("div", { className: " w-full rounded-lg", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-300 table-auto", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700    ", children: "Student ID" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Student Name" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Class/Semester" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Faculty" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Section" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Gender" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Mobile Number" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-medium text-primary-grey-700   ", children: "Status" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 w-10 text-left text-sm font-medium text-primary-grey-700  ", children: "Action" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: _jsx(RenderTable, { currentItems: currentItems }) })] }) }) }) }) }), _jsxs("nav", { className: " flex items-center justify-between py-3 bg-white border-t border-gray-200", "aria-label": "Pagination", children: [_jsx("div", { className: "sm:block hidden", children: _jsx("p", { className: "text-sm text-gray-700", children: message }) }), _jsxs("div", { className: "sm:justify-end flex justify-between flex-1", children: [_jsx("button", { disabled: indexOfFirstItem === 0, onClick: onPreviousPage, className: "disabled:opacity-80 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md", children: "Previous" }), _jsx("button", { disabled: indexOfLastItem >= people.length, onClick: onNextPage, className: "disabled:opacity-80 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md", children: "Next" })] })] })] }));
}
