import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import CloseOutlinedIcon from "@mui/icons-material/CloseOutlined";
export default function RenderTable({ type, index, setEntry, entry }) {
    return (_jsxs("tr", { children: [_jsx("td", { className: "p-2", children: _jsx("input", { type: "date", name: "date", id: "date", className: "mt-[6px] w-full p- rounded  focus:ring-primary-btn    border-primary-field shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }) }), _jsx("td", { className: "p-2", children: _jsx("input", { type: "text", className: "mt-[6px] w-full p- rounded  focus:ring-primary-btn    border-primary-field shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }) }), _jsx("td", { className: "p-2", children: _jsx("input", { type: "number", name: "ammount", id: "ammount", placeholder: "12000", className: "mt-[6px] w-full p- rounded  focus:ring-primary-btn   shadow-md border-primary-field  placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }) }), _jsx("td", { className: "p-2", children: _jsx("input", { type: "number", name: "discount", id: "discount", placeholder: "00", className: `mt-[6px] w-full p- rounded  focus:ring-primary-btn  ${type.entry !== "discount text-sm"
                        ? " border-primary-field  placeholder:text-primary-grey-400 "
                        : "  pointer-events-none border-primary-grey-400 bg-primary-grey-100 shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 "} ` }) }), _jsx("td", { className: "overscroll-none relative p-2", children: _jsx("input", { type: "number", name: "total", disabled: true, id: "total", placeholder: "12000", className: "mt-[6px] w-full p- rounded  focus:ring-primary-btn    border-primary-grey-400 bg-primary-grey-100 shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }) }), _jsx("td", { children: index === 0 ? (_jsx(_Fragment, {})) : (_jsx("div", { className: " text-primary-grey-700 w-fit p-1 mx-1 bg-white rounded-full shadow", onClick: () => {
                        // console.log(examName.slice(0, -1));
                        setEntry(entry.slice(0, -1));
                    }, children: _jsx(CloseOutlinedIcon, { fontSize: "inherit" }) })) })] }));
}
