import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import RenderTable from "./EntryTableRender";
import AddIcon from "@mui/icons-material/Add";
import { Link } from "react-router-dom";
export default function Table({ type }) {
    const [entry, setEntry] = useState([1]);
    useEffect(() => {
        type.entry === "discount" && setEntry([1]);
    }, [type]);
    return (_jsxs("div", { className: `${type ? "" : " pointer-events-none opacity-50   "}`, children: [_jsx("div", { className: ` ring-1 ring-black ring-opacity-5 mb-3 mt-6 min-w-full overflow-x-auto rounded-lg shadow `, children: _jsx("div", { className: " flex flex-col w-full rounded", children: _jsx("div", { className: " overflow-x-auto", children: _jsxs("table", { className: " min-w-full divide-y divide-gray-300 table-fixed", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { className: "text-primary-grey-700", children: [_jsx("th", { scope: "col", className: " py-3.5 px-3 text-left text-sm font-semibold text-primary-active", children: "Date" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-semibold text-primary-active", children: "Description" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-semibold text-primary-active", children: "Amount (Rs.)" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-semibold text-primary-active", children: "Discount (Rs.)" }), _jsx("th", { scope: "col", className: "px-3 py-3.5 text-left text-sm font-semibold text-primary-active", children: "Total amount (Rs.)" }), _jsx("th", { className: "" })] }) }), _jsxs("tbody", { className: " bg-white divide-y divide-gray-200", children: [entry.map((curr, index) => {
                                            return (_jsx(RenderTable, { type: type, index: index, setEntry: setEntry, entry: entry }));
                                        }), _jsx("tr", { className: "bg-gray-50 ", children: _jsx("td", { colSpan: "6", children: _jsx("div", { className: `w-fit flex p-2 mx-2 ml-auto cursor-pointer ${type.entry === "discount"
                                                        ? "pointer-events-none opacity-40 "
                                                        : " "}`, children: _jsxs("div", { className: "w-fit flex items-center justify-center", onClick: () => {
                                                            setEntry([...entry, 1]);
                                                        }, children: [_jsx("div", { className: "text-primary-btn mx-1", children: "Add new" }), _jsx(AddIcon, { className: "text-primary-btn", fontSize: "inherit" })] }) }) }) })] })] }) }) }) }), _jsxs("div", { className: "md:flex-row flex flex-col w-full", children: [_jsxs("div", { className: "grid items-center grid-cols-2 py-1", children: [_jsx("label", { htmlFor: "grandTotal", children: "Grand total :" }), _jsx("input", { type: "number", name: "grandTotal", disabled: true, id: "grandTotal", placeholder: "Rs.12000", className: "mt-[6px] w-36 p- rounded  focus:ring-primary-btn    border-primary-grey-400 bg-primary-grey-100 shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }), _jsx("label", { htmlFor: "paidAmount", children: "Paid ammount*: " }), _jsx("input", { type: "number", name: "paidAmmount", id: "paidAmmount", placeholder: "Rs.12000", className: "mt-[6px] w-36 p- rounded  focus:ring-primary-btn   shadow-md border-primary-field  placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" }), _jsx("label", { htmlFor: "due", children: "Due amount:" }), _jsx("input", { type: "number", name: "due", disabled: true, id: "due", placeholder: "Rs.12000", className: "mt-[6px] w-36 p- rounded  focus:ring-primary-btn    border-primary-grey-400 bg-primary-grey-100 shadow-md placeholder:text-primary-grey-400    text-primary-grey-700 text-sm" })] }), _jsxs("div", { className: " md:ml-3 md:my-0 md:mt-auto flex justify-between flex-1 my-3", children: [_jsxs("div", { className: "generate md:items-center flex", children: [_jsx("input", { type: "checkbox", className: "mr-3 rounded", id: "generateBill" }), _jsx("label", { htmlFor: "generateBill", className: "", children: "Generate Bill" })] }), _jsxs("div", { className: "btns w-fit ", children: [_jsx(Link, { to: "/fee/student-logsheet ", className: "secondary_btn", children: "Cancel" }), _jsx("div", { className: "primary_btn", children: "Submit" })] })] })] })] }));
}
