import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useContext } from "react";
import { Link } from "react-router-dom";
import StaffGeneralDetailsView from "../../../../../../../../contex/admin/staff/StaffGeneralDetailsView";
export default function AddressDetails() {
    const generaldetails = useContext(StaffGeneralDetailsView);
    const data = generaldetails?.data?.address;
    console.log(data, "address");
    return (_jsxs("div", { className: "my-6", children: [_jsxs("div", { className: "sm:flex sm:items-center my-3", children: [_jsx("div", { className: "sm:flex-auto", children: _jsx("h1", { className: "text-primary-grey-700 text-xl font-semibold", children: "Address details" }) }), _jsx("div", { className: "sm:mt-0 sm:ml-16 sm:flex-none mt-4", children: _jsx(Link, { to: "add", className: "primary_btn", children: "Edit" }) })] }), data?.same_as_permanent_address === undefined ||
                data?.same_as_permanent_address || (_jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-0 flex items-center", "aria-hidden": "true", children: _jsx("div", { className: "w-full border-t border-gray-300" }) }), _jsx("div", { className: "relative flex justify-center", children: _jsx("span", { className: "bg-white px-3 text-lg font-medium text-gray-900", children: "Permenant address" }) })] })), _jsxs("div", { className: "", children: [_jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Country:" }), _jsx("div", { children: data?.country_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Province:" }), _jsx("div", { children: data?.province_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "District:" }), _jsx("div", { children: data?.district_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "VDC municipality:" }), _jsx("div", { children: data?.vdc_municipality_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Ward:" }), _jsx("div", { children: data?.ward_no })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Tole:" }), _jsx("div", { children: data?.tole })] }), data?.same_as_permanent_address === undefined ||
                        data?.same_as_permanent_address || (_jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-0 flex items-center", "aria-hidden": "true", children: _jsx("div", { className: "w-full border-t border-gray-300" }) }), _jsx("div", { className: "relative flex justify-center", children: _jsx("span", { className: "bg-white px-3 text-lg font-medium text-gray-900", children: "Temporary address" }) })] })), data?.same_as_permanent_address === undefined ||
                        data?.same_as_permanent_address || (_jsxs("div", { className: "", children: [_jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Country:" }), _jsx("div", { children: data?.temp_country_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Province:" }), _jsx("div", { children: data?.temp_province_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "District:" }), _jsx("div", { children: data?.temp_district_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "VDC municipality:" }), _jsx("div", { children: data?.temp_vdc_municipality_name })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Ward:" }), _jsx("div", { children: data?.temp_ward_no })] }), _jsxs("div", { className: "flex flex-wrap justify-between", children: [_jsx("div", { className: "font-medium text-primary-grey-700  tracking-wide", children: "Tole:" }), _jsx("div", { children: data?.temp_tole })] })] }))] })] }));
}
