import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Suspense } from "react";
import { lazy } from "react";
import { Route, Routes } from "react-router-dom";
const ExamSlidebar = lazy(() => import("../../modules/admin/sidebar-activities/exam/ExamSlidebar"));
const ExamName = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/exam-name/exam-name/ExamName"));
const AddExamName = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/exam-name/add-exam-name/AddExamName"));
const GradeSystem = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/grade-system/grade-system/GradeSystem"));
const AddGradeSystem = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/grade-system/add-grade-system/AddGradeSystem"));
const ExamMarksName = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/exam-marks-name/exam-marks-name/ExamMarksName"));
const AddExamMarksName = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/exam-marks-name/add-exam-marks-name/AddExamMarksName"));
const AssignExam = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/assign-mark/assign-mark/AssignExam"));
const AssignAssignExam = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-setup/assign-mark/assign-assign-mark/AssignAssignExam"));
const MarkLedger = lazy(() => import("../../modules/admin/sidebar-activities/exam/mark-ledger/mark-ledger/MarkLedger"));
const ViewMarkLedger = lazy(() => import("../../modules/admin/sidebar-activities/exam/mark-ledger/view-mark-ledger/ViewMarkLedger"));
const OpenMarksheet = lazy(() => import("../../modules/admin/sidebar-activities/exam/mark-ledger/view-mark-ledger/open-marksheet/OpenMarksheet"));
const ExamShedule = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-shedule/exam-shedule/ExamShedule"));
const SheduleExamShedule = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-shedule/shedule-exam-shedule/SheduleExamShedule"));
const AddSheduleExamShedule = lazy(() => import("../../modules/admin/sidebar-activities/exam/exam-shedule/add-shedule-exam-shedule/AddSheduleExamShedule"));
const AdmitCard = lazy(() => import("../../modules/admin/sidebar-activities/exam/admit-card/admit-card/AdmitCard"));
const AssignAdmitCard = lazy(() => import("../../modules/admin/sidebar-activities/exam/admit-card/assign-admit-card/AssignAdmitCard"));
export default function ExamRoutes() {
    return (_jsx(Routes, { children: _jsxs(Route, { path: "/", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(ExamSlidebar, {}) }), children: [_jsxs(Route, { path: "exam-setup", children: [_jsx(Route, { path: "exam-name", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(ExamName, {}) }) }), _jsx(Route, { path: "exam-name/add", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AddExamName, {}) }) }), _jsx(Route, { path: "grading-system", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(GradeSystem, {}) }) }), _jsx(Route, { path: "grading-system/add", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AddGradeSystem, {}) }) }), _jsx(Route, { path: "exam-marks-name", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(ExamMarksName, {}) }) }), _jsx(Route, { path: "exam-marks-name/add", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AddExamMarksName, {}) }) }), _jsx(Route, { path: "assign-mark", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AssignExam, {}) }) }), _jsx(Route, { path: "assign-mark/assign/:classOfSchool/:section", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AssignAssignExam, {}) }) })] }), _jsx(Route, { path: "marks-ledger/view/:classOfSchool/:section/:studentName/:studentId", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(OpenMarksheet, {}) }) }), _jsx(Route, { path: "marks-ledger", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(MarkLedger, {}) }) }), _jsx(Route, { path: "marks-ledger/view/:classOfSchool/:section", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(ViewMarkLedger, {}) }) }), _jsx(Route, { path: "exam-shedule", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(ExamShedule, {}) }) }), _jsx(Route, { path: "exam-shedule/shedule/:examName", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(SheduleExamShedule, {}) }) }), _jsx(Route, { path: "exam-shedule/shedule/:examName/add", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AddSheduleExamShedule, {}) }) }), _jsx(Route, { path: "admit-card", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AdmitCard, {}) }) }), _jsx(Route, { path: "admit-card/assign/:classOfschool/:section", element: _jsx(Suspense, { fallback: "Loading", children: _jsx(AssignAdmitCard, {}) }) }), _jsx(Route, { path: "*", element: _jsxs("div", { className: "text-primary-grey-700 w-full mt-12 text-xl font-semibold text-center", children: ["Page not found-", location.pathname.replace("/", " ")] }) })] }) }));
}
