import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Fragment } from "react";
import { Link, useLocation } from "react-router-dom";
import { Disclosure, Menu, Popover, Transition } from "@headlessui/react";
import { BellIcon, Bars3Icon } from "@heroicons/react/24/outline";
import man from "./man-pic.png";
function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
}
export default function Navbar() {
    const location = useLocation().pathname;
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: " fixed top-0 z-[100] w-screen", children: _jsx(Disclosure, { as: "nav", className: "sm:border-none bg-white border-2 border-b shadow-md", children: ({ open }) => (_jsx("div", { className: "", children: _jsx("div", { className: "sm:px-4 px-4", children: _jsx("div", { className: "md:justify-between flex h-16", children: _jsxs("div", { className: " flex justify-between w-screen px-2", children: [_jsxs("div", { className: "md:flex-shrink-0 flex items-center", children: [_jsx("img", { className: " block w-auto h-10", src: "/logoHeader.png", alt: "Kinder garden school logo" }), _jsx(Link, { className: "w-36 text-logo sm:block hidden ml-2 text-base font-medium", to: "/admin/dashboard/", children: "Kindergarden Secondary School" })] }), _jsxs("div", { className: "lg:flex lg:space-x-8 hidden", children: [_jsx(Link, { to: "/teacherr/dashboard/dashboard", className: `${location.includes("/teacher/dashboard/dashboard")
                                                        ? "text-primary-grey-700 font-medium"
                                                        : "text-primary-grey-600 font-normal hover:text-primary-grey-700"}  inline-flex items-center px-1 pt-1  text-base `, children: "Dashboard" }), _jsx(Link, { to: "/admin/dashboard/event-calender", className: `${location.includes("event-calender")
                                                        ? "text-primary-grey-700 font-medium"
                                                        : "text-primary-grey-600 font-normal hover:text-primary-grey-700"}  inline-flex items-center px-1 pt-1  text-base `, children: "Event calander" }), _jsx(Link, { to: "/admin/dashboard/push-notification", className: `${location.includes("push-notification")
                                                        ? "text-primary-grey-700 font-medium"
                                                        : "text-primary-grey-600 font-normal hover:text-primary-grey-700"}  inline-flex items-center px-1 pt-1  text-base `, children: "Push Notification" }), _jsx(Link, { to: "fee/fee-payment", className: `${location.includes("fee/fee-payment")
                                                        ? "text-primary-grey-700 font-medium"
                                                        : "text-primary-grey-600 font-normal hover:text-primary-grey-700"}  inline-flex items-center px-1 pt-1  text-base `, children: "Fee Payment" }), _jsx(Link, { to: "fee/student-logsheet", className: `${location.includes("fee/student-logsheet")
                                                        ? "text-primary-grey-700 font-medium"
                                                        : "text-primary-grey-600 font-normal hover:text-primary-grey-700"}  inline-flex items-center px-1 pt-1  text-base `, children: "Logsheet" })] }), _jsxs("div", { className: "sm:flex lg:ml-0 lg:flex items-center hidden mx-2 ml-auto", children: [_jsxs("button", { type: "button", className: "text-primary-grey-600 hover:text-primary-grey-700 focus:outline-none flex-shrink-0 p-1 bg-white rounded-full", children: [_jsx("span", { className: "sr-only", children: "View notifications" }), _jsx(BellIcon, { className: "w-6 h-6", "aria-hidden": "true" })] }), _jsxs(Menu, { as: "div", className: "relative flex-shrink-0 ml-4", children: [_jsx("div", { children: _jsxs(Menu.Button, { className: "focus:outline-none ring-2 ring-offset-1 ring-primary-profile-circle flex text-base bg-white rounded-full", children: [_jsx("span", { className: "sr-only", children: "Open user menu" }), _jsx("img", { className: "w-8 h-8 rounded-full", src: man, alt: "man" })] }) }), _jsx(Transition, { as: Fragment, enter: "transition ease-out duration-100", enterFrom: "transform opacity-0 scale-95", enterTo: "transform opacity-100 scale-100", leave: "transition ease-in duration-75", leaveFrom: "transform opacity-100 scale-100", leaveTo: "transform opacity-0 scale-95", children: _jsxs(Menu.Items, { className: "ring-1 ring-black ring-opacity-5 focus:outline-none absolute right-0 w-48 py-1 mt-2 origin-top-right bg-white rounded-md shadow-sm", children: [_jsx(Menu.Item, { children: ({ active }) => (_jsx(Link, { to: "/admin/dashboard/profile", className: classNames(active ? "bg-gray-100" : "", "block px-4 py-2 text-base text-gray-700"), children: "Your Profile" })) }), _jsx(Menu.Item, { children: ({ active }) => (_jsx(Link, { to: "/admin/dashboard/settings", className: classNames(active ? "bg-gray-100" : "", "block px-4 py-2 text-base text-gray-700"), children: "Settings" })) }), _jsx(Menu.Item, { children: ({ active }) => (_jsx(Link, { href: "#", className: classNames(active ? "bg-gray-100" : "", "block px-4 py-2 text-base text-gray-700"), children: "Sign out" })) })] }) })] })] }), _jsxs(Popover, { className: "lg:hidden flex items-center", children: [_jsxs(Popover.Button, { className: " hover:text-primary-grey-700 focus:outline-primary-grey-200 focus:outline inline-flex items-center justify-center p-2 rounded-md", children: [_jsx("span", { className: "sr-only", children: "Open main menu" }), _jsx(Bars3Icon, { className: " block w-6 h-6", "aria-hidden": "true" })] }), _jsx(Popover.Panel, { className: "lg:hidden absolute right-0 top-[66px] w-40 h-screen", children: _jsxs("div", { className: "h-5/6 min-h-fit bg-primary-grey-100 pt-2 pb-3 space-y-1 shadow-md", children: [_jsx(Popover.Button, { as: "a", className: `${location.includes("dashboard")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: _jsx(Link, { to: "/admin/dashboard/", children: " Dashboard" }) }), _jsxs(Popover.Button, { as: "a", className: `${location.includes("event-calender")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: [_jsx(Link, { to: "/admin/dashboard/", children: " Event" }), " Calender"] }), _jsx(Popover.Button, { as: "a", className: `${location.includes("projects")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: _jsx(Link, { to: "/admin/dashboard/", children: " Projects" }) }), _jsxs(Popover.Button, { as: "a", className: `${location.includes("push-notification")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: [_jsx(Link, { to: "/admin/dashboard/", children: " Push" }), "Notification"] }), _jsxs(Popover.Button, { as: "a", className: `${location.includes("fee-payment")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: [_jsx(Link, { to: "/admin/dashboard/", children: " Fee" }), " Payment"] }), _jsx(Popover.Button, { as: "a", className: `${location.includes("logsheet")
                                                                    ? "bg-primary-grey-200 border-primary-grey-300 font-normal-700 cursor-pointer w-full text-primary-grey-700 block py-2 pl-3 pr-4 text-base border-l-4"
                                                                    : "bg-primary-grey-100 font-normal-700  hover:bg-primary-grey-200 w-full hover:border-primary-grey-300  cursor-pointer text-primary-grey-600 block py-2 pl-3 pr-4 text-base hover:border-l-4"}  inline-flex items-center px-1 pt-1  text-base `, children: _jsx(Link, { to: "/admin/dashboard/", children: " Logsheet" }) })] }) })] })] }) }) }) })) }) }), _jsx("div", { className: "mb-16" })] }));
}
